### ISSUE TITLE
Utilize materialized view for OCP on All report queries

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1705] opened 2020-02-06 15:21 UTC
## User Story
As a customer running a large OCP footprint on multiple clouds I would like OCP on All reporting queries to return quickly at scale, so that when viewing the dashboard the experience does not suffer from long request load times.

## Impacts
API

## Assumptions
- This one is a little different than the other materialized views in that OCP on All is already a materialized view. We may want to re-work the way this works?
- We will need to select the right model for the query handler based on the query: https://github.com/project-koku/koku/blob/2879d253f1bc8daee5f67bddc8709f3120408f26/koku/api/report/aws/query_handler.py#L120

## Implementation Details
Changes should be modeled on the following PRs that added materialized views for AWS queries:
https://github.com/project-koku/koku/pull/1495
https://github.com/project-koku/koku/pull/1554
https://github.com/project-koku/koku/pull/1645

## Acceptance Criteria

- [ ] Verify that existing test cases (unit and QE) still pass
- [ ] Views exist for cost, 
   - reports/openshift/infrastructures/all/costs/
   - reports/openshift/infrastructures/all/costs/?group_by[project] 
   - reports/openshift/infrastructures/all/costs/?group_by[cluster]
- [x] Views exist for compute API
   - reports/openshift/infrastructures/all/instance-types/
- [x] Views exist for storage API
   - reports/openshift/infrastructures/all/storage
- [x] Views exist for database API
   - reports/openshift/infrastructures/all/costs/?filter[service]='AmazonRDS','AmazonDynamoDB','AmazonElastiCache','AmazonNeptune','AmazonRedshift','AmazonDocumentDB'
- [x] Views exist for network API
   - reports/openshift/infrastructures/all/costs/?filter[service]='AmazonVPC','AmazonCloudFront','AmazonRoute53','AmazonAPIGateway'

**Comment by Red-HAP** [comment] 2020-03-09 22:39
@adberglund 
I've spent some time looking at the view definitions and I'm getting a bit tripped up in my thought process for the optimization. While I have identified a possible missing index on those MVs, I keep thinking are these to be the foundation for views like aws (account, region, service) or are you looking to create something totally new. If the latter, should we defer change of that nature to post GA?

Otherwise, would it make more sense to test the improvements of the daily, daily_summary tables at a far larger scale?

**Comment by Red-HAP** [comment] 2020-03-12 19:11
I started with this request:
```
/api/cost-management/v1/reports/openshift/infrastructures/all/costs/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=3&group_by[project]=*
```
Which created the following query (among others):
```
SELECT DATE_TRUNC('month', "reporting_ocpallcostlineitem_project_daily_summary"."usage_start") AS "date",
       COALESCE(MAX("reporting_ocpallcostlineitem_project_daily_summary"."currency_code"), 'USD') AS "cost_units",
       CONCAT("reporting_ocpallcostlineitem_project_daily_summary"."namespace", 'EEK') AS "project",
       SUM((COALESCE("reporting_ocpallcostlineitem_project_daily_summary"."pod_cost", 0.01) + COALESCE("reporting_ocpallcostlineitem_project_daily_summary"."project_markup_cost", 0.001))) AS "cost",
       SUM("reporting_ocpallcostlineitem_project_daily_summary"."pod_cost") AS "infrastructure_cost",
       SUM(0.01) AS "derived_cost",
       SUM(COALESCE("reporting_ocpallcostlineitem_project_daily_summary"."project_markup_cost", 0.01)) AS "markup_cost",
       ARRAY_AGG(DISTINCT COALESCE("reporting_ocpallcostlineitem_project_daily_summary"."cluster_alias", "reporting_ocpallcostlineitem_project_daily_summary"."cluster_id")) AS "clusters",
       ROW_NUMBER() OVER (PARTITION BY DATE_TRUNC('month', "reporting_ocpallcostlineitem_project_daily_summary"."usage_start")
                          ORDER BY SUM((COALESCE("reporting_ocpallcostlineitem_project_daily_summary"."pod_cost", 0) + COALESCE("reporting_ocpallcostlineitem_project_daily_summary"."project_markup_cost", 0))) DESC) AS "rank"
FROM "reporting_ocpallcostlineitem_project_daily_summary"
WHERE ("reporting_ocpallcostlineitem_project_daily_summary"."usage_start" >= '2020-01-01'::date
       AND "reporting_ocpallcostlineitem_project_daily_summary"."usage_end" <= '2020-02-29'::date)
GROUP BY DATE_TRUNC('month', "reporting_ocpallcostlineitem_project_daily_summary"."usage_start"),
         CONCAT("reporting_ocpallcostlineitem_project_daily_summary"."namespace", 'EEK')
```
(Silly values used for prepared statement variables)
This query's filter returns most, if not all, of the data from the materialized view. 

And I found that PG is using a swq scan, but the request is pretty much asking for all of the data in the materialized view, so it's logical for PG to do this. Once you have more than 2 months of data (I experimented with 6-7 months) PG will use the indexes, but having to pluck 2 months of (unrealistically skewed) data out of that larger set, you get a query execution time exceeding the target API response time. So the issue is still one of either better segmenting the data or utilizing queries that are requesting data with more granular filtering.

This was illustrated even better when using this request:
```
/api/cost-management/v1/reports/openshift/infrastructures/all/instance-types/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=daily&filter[service]=AmazonEC2
```

Which generated this query among others:
```
SELECT "reporting_ocpallcostlineitem_daily_summary"."instance_type",
       DATE_TRUNC('day', "reporting_ocpallcostlineitem_daily_summary"."usage_start") AS "date",
       COALESCE(MAX("reporting_ocpallcostlineitem_daily_summary"."currency_code"), 'USD') AS "cost_units",
       COALESCE(MAX("reporting_ocpallcostlineitem_daily_summary"."unit"), 'X') AS "usage_units",
       SUM((COALESCE("reporting_ocpallcostlineitem_daily_summary"."unblended_cost", 0.1) + COALESCE("reporting_ocpallcostlineitem_daily_summary"."markup_cost", 0.1))) AS "cost",
       SUM("reporting_ocpallcostlineitem_daily_summary"."unblended_cost") AS "infrastructure_cost",
       SUM(0.1) AS "derived_cost",
       SUM(COALESCE("reporting_ocpallcostlineitem_daily_summary"."markup_cost", 0.01)) AS "markup_cost",
       COUNT(DISTINCT "reporting_ocpallcostlineitem_daily_summary"."resource_id") AS "count",
       'X' AS "count_units",
       SUM("reporting_ocpallcostlineitem_daily_summary"."usage_amount") AS "usage",
       ARRAY_AGG(DISTINCT COALESCE("reporting_ocpallcostlineitem_daily_summary"."cluster_alias", "reporting_ocpallcostlineitem_daily_summary"."cluster_id")) AS "clusters"
FROM "reporting_ocpallcostlineitem_daily_summary"
WHERE ("reporting_ocpallcostlineitem_daily_summary"."usage_start" >= '2020-02-01'::date
       AND "reporting_ocpallcostlineitem_daily_summary"."usage_end" <= '2020-03-31'::date
       AND "reporting_ocpallcostlineitem_daily_summary"."instance_type" IS NOT NULL
       AND UPPER("reporting_ocpallcostlineitem_daily_summary"."product_code"::text) LIKE UPPER('abl'))
GROUP BY "reporting_ocpallcostlineitem_daily_summary"."instance_type",
         DATE_TRUNC('day', "reporting_ocpallcostlineitem_daily_summary"."usage_start")
```

And also produced a query plan that utilized a seq scan:
```
                                                                                        QUERY PLAN                                                                                        
------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=6389.78..6389.85 rows=1 width=422) (actual time=42.335..42.335 rows=0 loops=1)
   Group Key: instance_type, (date_trunc('day'::text, (usage_start)::timestamp with time zone))
   ->  Sort  (cost=6389.78..6389.79 rows=1 width=1517) (actual time=42.332..42.332 rows=0 loops=1)
         Sort Key: instance_type, (date_trunc('day'::text, (usage_start)::timestamp with time zone))
         Sort Method: quicksort  Memory: 25kB
         ->  Gather  (cost=1000.00..6389.77 rows=1 width=1517) (actual time=42.319..44.477 rows=0 loops=1)
               Workers Planned: 2
               Workers Launched: 2
               ->  Parallel Seq Scan on reporting_ocpallcostlineitem_daily_summary  (cost=0.00..5389.67 rows=1 width=1517) (actual time=32.964..32.964 rows=0 loops=3)
                     Filter: ((instance_type IS NOT NULL) AND (usage_start >= '2020-02-01'::date) AND (usage_end <= '2020-03-31'::date) AND (upper((product_code)::text) ~~ 'ABL'::text))
                     Rows Removed by Filter: 38667
 Planning time: 0.457 ms
 Execution time: 44.659 ms
```

This query is using the large date range encompassing pretty much the whole table, but is also using another filter criteria with the LIKE operation. It still used a seq scan and I re-timed it in `psql` at around  17.66 - 44.66 ms.

By leaving the view definition alone and simply adding an index to cover the like operation (using gin_trgm_ops), I was able to **cut the execution time down to 0.17 - 0.26 ms**.
```
create index "ocpallcstdlysumm_prod_code" on reporting_ocpallcostlineitem_daily_summary using gin (upper(product_code::text) gin_trgm_ops);
```
```
                                                                          QUERY PLAN                                                                           
---------------------------------------------------------------------------------------------------------------------------------------------------------------
 GroupAggregate  (cost=1666.04..1666.10 rows=1 width=422) (actual time=0.107..0.107 rows=0 loops=1)
   Group Key: instance_type, (date_trunc('day'::text, (usage_start)::timestamp with time zone))
   ->  Sort  (cost=1666.04..1666.04 rows=1 width=1517) (actual time=0.106..0.106 rows=0 loops=1)
         Sort Key: instance_type, (date_trunc('day'::text, (usage_start)::timestamp with time zone))
         Sort Method: quicksort  Memory: 25kB
         ->  Bitmap Heap Scan on reporting_ocpallcostlineitem_daily_summary  (cost=48.35..1666.03 rows=1 width=1517) (actual time=0.101..0.101 rows=0 loops=1)
               Recheck Cond: (upper((product_code)::text) ~~ 'ABL'::text)
               Filter: ((instance_type IS NOT NULL) AND (usage_start >= '2020-02-01'::date) AND (usage_end <= '2020-03-31'::date))
               ->  Bitmap Index Scan on ocpallcstdlysumm_prod_code  (cost=0.00..48.35 rows=580 width=0) (actual time=0.100..0.100 rows=0 loops=1)
                     Index Cond: (upper((product_code)::text) ~~ 'ABL'::text)
 Planning time: 0.242 ms
 Execution time: 0.167 ms
```

So the indexing and changing the queries was a good start, but, wherever possible, more granular filtering will produce better access times. Where that is not possible, then continuing to segment the data should help. Utilizing partitioning by time (specifically, by customer, then by time) could provide a greater benefit at larger scale.

This may mean that our UI or table structures may need to change in order to produce a consistently fast response even as data sizes increase.

Needless to say that I will be including the product code index as part of this ticket.

**Comment by Red-HAP** [comment] 2020-03-13 17:56
This is also a case to get production monitoring in place for the database queries. 

This would mean setting up the RDS database to operate with the same or similar parameters and libraries that have been set for development.

I can continue to try to mimic that traffic in dev, but to be able to see the poorly running queries in production would be an invaluable resource.

We can evaluate a product like VividCortex or simply start with something similar to the grafana dashboards that I have set in dev, but if we want to monitor other things like locks or performance over time, then we will have to use a service or have a second database for query analysis.

**Comment by Red-HAP** [comment] 2020-03-13 20:38
OK, so I think the view combining ocp on aws, azure data (reporting_ocpall*) is about as good as it's going to get short term.

However, the ocpusagelineitem_daily, daily_summary tables I think need some work.

Playing around with a new structure that will aggregate a lot of the data. Whether we want to change the existing table structure or create new materialized views shoud be reviewed.

The structure I've started playing with is here:
```
create table reporting_ocpusagelineitem_daily_aggregate as 
    SELECT report_period_id,
        array_agg(distinct cluster_id order by cluster_id) filter (where cluster_id is not null) as cluster_id,
        array_agg(distinct cluster_alias order by cluster_alias) filter (where cluster_alias is not null) as cluster_alias,
        'Pod'::text as data_source,
        array_agg(distinct namespace order by namespace) filter (where namespace is not null) as namespace,
        array_agg(distinct pod order by pod) filter (where pod is not null) as pod,
        array_agg(distinct node order by node) filter (where node is not null) as node,
        array_agg(distinct resource_id order by resource_id) filter (where resource_id is not null) as resource_id,
        usage_start,
        usage_end,
        '{}'::jsonb as pod_labels,
        sum(1.0) as pod_usage_cpu_core_hours,
        sum(1.0) as pod_request_cpu_core_hours,
        sum(1.0) as pod_limit_cpu_core_hours,
        sum(1.0) as pod_usage_memory_gigabyte_hours,
        sum(1.0) as pod_request_memory_gigabyte_hours,
        sum(1.0) as pod_limit_memory_gigabyte_hours,
        sum(1.0) as node_capacity_cpu_cores,
        sum(1.0) as node_capacity_cpu_core_hours,
        sum(1.0) as node_capacity_memory_gigabytes,
        sum(1.0) as node_capacity_memory_gigabyte_hours,
        sum(1.0) as cluster_capacity_cpu_core_hours,
        sum(1.0) as cluster_capacity_memory_gigabyte_hours,
        sum(1.0) as total_capacity_cpu_core_hours,
        sum(1.0) as total_capacity_memory_gigabyte_hours
    FROM reporting_ocpusagelineitem_daily
   group
      by report_period_id,
         usage_start, 
         usage_end;
```

**Comment by Red-HAP** [comment] 2020-03-30 18:34
Work for this ticket was actually done on #1962. This ticket should be closed.

**Comment by lcouzens** [comment] 2020-04-03 11:04
Verified

**Closed by lcouzens** 2020-04-03 11:04 UTC
Labels: Database, enhancement
