### ISSUE TITLE
Return 'Others' when applying group_by tag keys

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#715] opened 2019-03-06 23:38 UTC
## User Story
As a user, I want to see an 'Others' item in the AWS/OCP details page, when group_by tag keys is applied. 

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- 
- 

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/openshift/charges/ |
 | **Body** |  |
 | **Response** | |

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/aws/costs/ |
 | **Body** |  |
 | **Response** | |

## UI Details
This would be similar to the AWS instance API, used for on the top 5 in the UI's overview page. That is, the API would return an 'Others' report item, showing the remaining total.

Per my discussion with Natalie, the 'Others' total would be the total cost minus the cost returned for the group_by tag keys. The idea is to display this along with the other table data, so this must come from the server-side to work with pagination, filtering, and sorting.

Currently, the group_by appears to return a cost filtered by tag keys. Natalie expects that we show the total cost here Vs a filtered cost. That is, group_by project, node, and cluster all show the same total cost.

Mock: https://redhat.invisionapp.com/share/HEO4ISHAT8Z#/screens/350493391

![screen shot 2019-03-07 at 10 33 26 am](https://user-images.githubusercontent.com/17481322/53968117-77409680-40c4-11e9-9905-fdacb5cebbee.png)

## Acceptance Criteria

- [ ] Functionality similar to the AWS instance API
- [ ] 'Others' total would be the total projects cost minus the cost returned for the group_by tag keys

**Comment by chambridge** [comment] 2019-03-13 10:14
Per conversation with Sergio, this is a post Summit need.

**Comment by adberglund** [comment] 2019-09-30 16:40
It's possible this can be handled by eliminating an exclusion in the reporting code. See: https://github.com/project-koku/koku/blob/master/koku/api/report/queries.py#L312

I have not assessed the ramifications of removing this code, but it is a good starting point for seeing if getting everything not tagged returned would work.

**Comment by maskarb** [comment] 2019-10-25 13:23
@dlabrecq 

Returning 'others' can be accomplished through a small change to the _query_ itself which would require a UI change. The above mock looks like it uses the query `group_by[tag:environment]=*` to return everything excluding the 'Un-tagged' field. If we change the query to `group_by[or:tag:environment]=*`, it would return a 'no-environment' field. 

Here is an example using our AWS on CI with the `name` tag. This query [`https://ci.cloud.redhat.com/api/cost-management/v1/reports/aws/costs/?filter[time_scope_value]=-1&group_by[tag:name]=*`](https://ci.cloud.redhat.com/api/cost-management/v1/reports/aws/costs/?filter[time_scope_value]=-1&group_by[tag:name]=*) returns:

```
"data": [
        {
            "date": "2019-10",
            "names": [
                {
                    "name": "ckyrouac-test-dev",
                    "values": [
                        {
                            "name": "ckyrouac-test-dev",
                            "date": "2019-10",
                            "cost": {
                                "value": 41.356800603,
                                "units": "USD"
                            },
                            "infrastructure_cost": {
                                "value": 41.356800603,
                                "units": "USD"
                            },
                            "derived_cost": {
                                "value": 0.0,
                                "units": "USD"
                            },
                            "markup_cost": {
                                "value": 0.0,
                                "units": "USD"
                            }
                        }
                    ]
                }
            ]
        }
    ]
```
Here, the 'no-tag' is missing, but if we add the `or` to the group_by query, e.g. [`https://ci.cloud.redhat.com/api/cost-management/v1/reports/aws/costs/?filter[time_scope_value]=-1&group_by[or:tag:name]=*`](https://ci.cloud.redhat.com/api/cost-management/v1/reports/aws/costs/?filter[time_scope_value]=-1&group_by[or:tag:name]=*) we return the following:

```
"data": [
        {
            "date": "2019-10",
            "names": [
                {
                    "name": "no-name",
                    "values": [
                        {
                            "name": "no-name",
                            "date": "2019-10",
                            "cost": {
                                "value": 47894.910801896,
                                "units": "USD"
                            },
                            "infrastructure_cost": {
                                "value": 47894.910801896,
                                "units": "USD"
                            },
                            "derived_cost": {
                                "value": 0.0,
                                "units": "USD"
                            },
                            "markup_cost": {
                                "value": 0.0,
                                "units": "USD"
                            }
                        }
                    ]
                },
                {
                    "name": "ckyrouac-test-dev",
                    "values": [
                        {
                            "name": "ckyrouac-test-dev",
                            "date": "2019-10",
                            "cost": {
                                "value": 41.356800603,
                                "units": "USD"
                            },
                            "infrastructure_cost": {
                                "value": 41.356800603,
                                "units": "USD"
                            },
                            "derived_cost": {
                                "value": 0.0,
                                "units": "USD"
                            },
                            "markup_cost": {
                                "value": 0.0,
                                "units": "USD"
                            }
                        }
                    ]
                }
            ]
        }
    ]
```

I think making this change on the UI side _could_ be the most straightforward way to implement the return of 'others.'

**Comment by adberglund** [comment] 2019-10-29 20:13
@maskarb Let's write a unit test to show that the other category can show up when using this so we don't break the functionality later, and then pass this along to QE.

**Comment by dchorvat1** [comment] 2019-11-12 09:37
verified, 60bc14d9f9ebe5db40d3ff5a7cbd7be000c6afd4

**Comment by dlabrecq** [comment] 2019-11-12 15:59
@maskarb When applying the 'environment' tag; for example, I see the 'no-environment' name in the results. I can reproduce this with AWS, Azure, and OpenShift on AWS; however, I do not see this behavior with OpenShift.

/v1/reports/openshift/costs/?delta=cost&filter[limit]=10&group_by[or:tag:environment]=*&order_by[cost]=desc&filter[offset]=0&filter[resolution]=monthly&filter[time_scope_units]=month&filter[time_scope_value]=-1

![Screen Shot 2019-11-12 at 10 58 07 AM](https://user-images.githubusercontent.com/17481322/68687543-5fff5600-053b-11ea-9192-4617d8c40c1a.png)

If this was not intended to work with OpenShift, feel free to close

**Comment by lcouzens** [comment] 2019-11-15 17:35
@adberglund Any comment on this is this the expected behaviour ? If so you can probably just close it as Daniel already verified this before it got reopened with the questions. ^

**Comment by dlabrecq** [comment] 2019-11-15 18:29
It sounds like OpenShift didn't have this behavior because there were tags for everything and there was no "other" category.

**Closed** 2019-11-15 18:33 UTC
Labels: Koku'(x), enhancement
