### ISSUE TITLE
Some users can see accounts of other users

### ISSUE THREAD

**Issue by chargio** [project-koku/koku#869] opened 2019-05-22 10:39 UTC
**Describe the bug**
In a new created organisation, with a minor number of users, the data is available to users that are not part of the organisation

**To Reproduce**
Data, not a bug in the interface

**Expected behavior**
The data should not be visible in the demo account.

**Screenshots**
Not applicable

**Context (please complete the following information):**

**Additional context**
Red Hat Account Number: 6234926
New data has been added there
The account 591058 can see the data added, it should not be possible

**Comment by blentz** [comment] 2019-05-23 15:08
There's some questions about whether this is a bug or a misconfiguration.

QE or Engineering should validate the bug exists. If we can't reproduce, we can close this issue.

**Comment by blentz** [comment] 2019-06-03 14:18
I'm not able to reproduce this issue.

If this happens again, let's capture a copy of the DB for analysis.

**Closed by blentz** 2019-06-03 14:18 UTC
Labels: bug, priority - high
