### ISSUE TITLE
Adding OCP provider while having AZURE provider in the database results in a 500

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1137] opened 2019-09-19 12:50 UTC
**Describe the bug**
Adding OCP provider while having AZURE provider in the environment failed with plain 500 server error result.

**To Reproduce**
1. Successfully add an azure provider
2. Add an OCP provider
3. See error

**Expected behavior**
Both providers should be added correctly

**Additional context**
Tested on CI
This issue happened even if I tried to add the OCP provider on a different account (AZURE provider was on `dchorvat` and I couldn't add the OCP provider even on `insights-qa`)

**Comment by blentz** [comment] 2019-09-19 19:17
With my local environment (built off of master, commit f6b31b53d8), I could not reproduce this:

```
/scripts/create_test_customer.py -f scripts/blentz.yaml.all
Config: {'customer': {'account_id': 10001, 'email': 'blentz+hccm-test@redhat.com', 'user': 'test_customer', 'providers': {'aws_provider': {'provider_type': 'AWS', 'provider_name': 'Test Provider', 'authentication': {'provider_resource_name': 'arn:aws:iam::589173575009:role/CostManagement'}, 'billing_source': {'bucket': 'cost-usage-bucket'}}, 'ocp_provider': {'provider_name': 'OCP Test Provider', 'provider_type': 'OCP', 'authentication': {'provider_resource_name': 'my-ocp-cluster-1'}, 'billing_source': {}}, 'azure_provider': {'provider_name': 'Azure Test Provider', 'provider_type': 'AZURE', 'authentication': {'credentials': {'subscription_id': '2639de71-ca37-4a17-a104-17665a50e7fc', 'tenant_id': 'ae4f8f55-f1a8-4080-9aa8-10779e4113e7', 'client_id': 'd6b607d7-d07a-4ca0-b81d-39631f73234a', 'client_secret': 'cbde6308-bab1-489a-afc6-5280fb5cf793'}}, 'billing_source': {'data_source': {'resource_group': 'RG1', 'storage_account': 'mysa1'}}}}}, 'koku': {'host': 'koku-myproject.192.168.42.172.nip.io', 'port': 80, 'prefix': 'api'}, 'config_file': 'scripts/blentz.yaml.all', 'bypass_api': False}

Adding customer...
Response: [200] {"meta":{"count":10,"filter":{"time_scope_value":"-10","time_scope_units":"day","resolution":"daily"},"total":{"infrastructure_cost":{"value":0,"units":"USD"},"derived_cost":{"value":0,"units":"USD"},"cost":{"value":0,"units":"USD"}}},"links":{"first":"/api/v1/reports/aws/costs/?limit=100&offset=0","next":null,"previous":null,"last":"/api/v1/reports/aws/costs/?limit=100&offset=0"},"data":[{"date":"2019-09-10","values":[]},{"date":"2019-09-11","values":[]},{"date":"2019-09-12","values":[]},{"date":"2019-09-13","values":[]},{"date":"2019-09-14","values":[]},{"date":"2019-09-15","values":[]},{"date":"2019-09-16","values":[]},{"date":"2019-09-17","values":[]},{"date":"2019-09-18","values":[]},{"date":"2019-09-19","values":[]}]}

Adding {'provider_type': 'AWS', 'provider_name': 'Test Provider', 'authentication': {'provider_resource_name': 'arn:aws:iam::589173575009:role/CostManagement'}, 'billing_source': {'bucket': 'cost-usage-bucket'}}...
Response: [201] {"uuid":"7e47e42c-0db0-4596-b237-b30b3e5dc5b7","name":"Test Provider","type":"AWS","authentication":{"uuid":"40a40d17-4a39-454c-b806-6e1e15588229","provider_resource_name":"arn:aws:iam::589173575009:role/CostManagement","credentials":{}},"billing_source":{"uuid":"7ea0f667-d841-4249-a509-ef831ed659df","bucket":"cost-usage-bucket","data_source":{}},"customer":{"uuid":"bdc3af07-a3ad-4330-b103-6e255aec14fb","account_id":"10001","date_created":"2019-09-13T19:28:52.733139Z"},"created_by":{"uuid":"5fe8762a-add0-4a2b-a7f5-0f53c19c750b","username":"user_dev","email":"user_dev@foo.com"},"created_timestamp":"2019-09-19T19:14:03.311948Z"}

Adding {'provider_name': 'OCP Test Provider', 'provider_type': 'OCP', 'authentication': {'provider_resource_name': 'my-ocp-cluster-1'}, 'billing_source': {}}...
Response: [201] {"uuid":"9c59adda-da34-4bc5-860b-342701d75f5a","name":"OCP Test Provider","type":"OCP","authentication":{"uuid":"095532e2-0b5d-4fd6-bc92-ad84bd23d857","provider_resource_name":"my-ocp-cluster-1","credentials":{}},"billing_source":{"uuid":"00e848cd-05be-4e4f-9d8e-254c9652c6d7","bucket":"","data_source":{}},"customer":{"uuid":"bdc3af07-a3ad-4330-b103-6e255aec14fb","account_id":"10001","date_created":"2019-09-13T19:28:52.733139Z"},"created_by":{"uuid":"5fe8762a-add0-4a2b-a7f5-0f53c19c750b","username":"user_dev","email":"user_dev@foo.com"},"created_timestamp":"2019-09-19T19:14:03.547211Z"}

Adding {'provider_name': 'Azure Test Provider', 'provider_type': 'AZURE', 'authentication': {'credentials': {'subscription_id': '2639de71-ca37-4a17-a104-17665a50e7fc', 'tenant_id': 'ae4f8f55-f1a8-4080-9aa8-10779e4113e7', 'client_id': 'd6b607d7-d07a-4ca0-b81d-39631f73234a', 'client_secret': 'cbde6308-bab1-489a-afc6-5280fb5cf793'}}, 'billing_source': {'data_source': {'resource_group': 'RG1', 'storage_account': 'mysa1'}}}...
Response: [400] {"errors":[{"detail":"A Provider already exists with that Authentication and Billing Source","source":"Error","status":400}]}
```

**Comment by blentz** [comment] 2019-09-24 17:01
Re-confirmed my results with a build against master at 6ee93c458911. I can't reproduce this issue. Closing.

**Closed by blentz** 2019-09-24 17:01 UTC
Labels: azure, bug, priority - high
