### ISSUE TITLE
Adding Azure provider without some of the credentials results in 500

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1136] opened 2019-09-19 09:40 UTC
**Describe the bug**
POST request with an Azure provider with some of the credentials missing results in 500 response from the server, with no error message. This happens if we leave out any of the 
`subscription_id/tenant_id/client_id/client_secret` fields.

**To Reproduce**
1. POST
```
{
    "name": "test_azure_source",
    "type": "AZURE",
    "authentication": {
        "credentials": {
            "tenant_id" :<tenant id>,
            "client_id": <client id>,
            "client_secret": <client secret>
        }
    },
    "billing_source": {
        "data_source": {
            "resource_group": <resource group>,
            "storage_account": <storage account>
        }
    }
}
```
to `/providers/` with those fields filled out (subscription_id is missing in this case)
2. See error

**Expected behavior**
We should get a 400 response with an error message describing the bad request

**Additional context**
Tested on CI

**Comment by blentz** [comment] 2019-09-19 20:37
I was not able to reproduce this. 

With a request of:
```
http://koku-myproject.192.168.42.172.nip.io/api/v1/providers/?name=test_source&type=AZURE&authentication={"credentials": {"tenant_id": "9a3b2740-6e32-4807-a0c5-f1528c21a13e" }}&billing_source={"data_source": {"resource_group": "myrg1", "storage_account": "mysa1"}}
```

I got a 201 response:

```
172.17.0.1 - - [19/Sep/2019:20:33:03 +0000] "POST /api/v1/providers/?name=test_source&type=AZURE&authentication=%7B%22credentials%22:%20%7B%22tenant_id%22:%20%229a3b2740-6e32-4807-a0c5-f1528c21a13e%22%20%7D%7D&billing_source=%7B%22data_source%22:%20%7B%22resource_group%22:%20%22myrg1%22,%20%22storage_account%22:%20%22mysa1%22%7D%7D HTTP/1.1" 201 633 "-" "PostmanRuntime/7.17.1"
```

**Comment by dchorvat1** [comment] 2019-09-19 21:11
I just tried that on CI/QA/PROD and the request returned the exact 500 response in all of the environments, could you look at any of those?

**Comment by blentz** [comment] 2019-09-19 21:42
@dchorvat1 - Will do. Point being, the solution for this is that we probably need to update the environments to roll out the code with the fixes to this issue. I don't think any additional work will be required, but I will verify that. :)

**Comment by blentz** [comment] 2019-09-24 17:05
I've tested using a build from master at 6ee93c458911, I could not reproduce this issue.

I'm closing this. If it reoccurs, please re-open the issue.

**Comment by blentz** [comment] 2019-09-25 15:04
Got some extra info from Dan and finally reproduced the bug.

**Closed** 2019-09-27 17:02 UTC
Labels: azure, bug, priority - high
