### ISSUE TITLE
Intermittent Test Failures 

### ISSUE THREAD

**Issue by adberglund** [project-koku/koku#1011] opened 2019-08-16 19:16 UTC
**Describe the bug**
A test in the report charge updater is intermittently failing. Unfortunately the parallel execution option on the tests is making reading these failures a little more difficult at the moment. This will hopefully be fixed with the introduction of `tblib`, but we might be able to track down the test that is failing sometimes. 

```python
test_update_summary_charge_info_cpu_real_rates (masu.test.processor.ocp.test_ocp_report_charge_updater.OCPReportChargeUpdaterTest) failed:
    AssertionError('0.00027 != 0.00028',)
```

Additional intermittent failures
```python
======================================================================
FAIL: test_compose_with_and_operator (api.report.test.tests_query_filter.QueryFilterCollectionTest)
Test the compose() method with and operator on the filter.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-koku/koku/koku/api/report/test/tests_query_filter.py", line 208, in test_compose_with_and_operator
    self.assertEqual(qf_coll.compose(), expected)
AssertionError: <Q: (AND: ('accept__three__past', 'hit'))> != <Q: (AND: ('accept__three__past', 'hit'), ('accept__three__past', 'hit'))>
```
```python
======================================================================
FAIL: test_update_summary_charge_info_cpu_real_rates (masu.test.processor.ocp.test_ocp_report_charge_updater.OCPReportChargeUpdaterTest)
Test that OCP charge information is updated for cpu from the right provider uuid.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-koku/koku/koku/masu/test/processor/ocp/test_ocp_report_charge_updater.py", line 862, in test_update_summary_charge_info_cpu_real_rates
    round(float(item.pod_charge_cpu_core_hours), 5))
AssertionError: 0.00012 != 0.00013
```

**Comment by adberglund** [comment] 2019-08-29 15:05
I think it's worth a quick investigation on the `test_compose_with_and_operator` test to see if it jumps out at us. The rounding errors have been tackled.

**Comment by maskarb** [comment] 2019-08-29 18:11
With parallel on:
```python
FAIL: test_execute_query_group_by_node (api.report.test.ocp.tests_views.OCPReportViewTest)
Test that grouping by node filters data.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/mskarbek/Documents/code/koku/koku/api/report/test/ocp/tests_views.py", line 914, in test_execute_query_group_by_node
    self.assertEqual(node.get('node'), node_of_interest)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 829, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 1203, in assertMultiLineEqual
    self.fail(self._formatMessage(msg, standardMsg))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 670, in fail
    raise self.failureException(msg)
AssertionError: 'measure' != 'a'
- measure
+ a
```

**Comment by maskarb** [comment] 2019-08-30 15:55
During Travis build:
```python
======================================================================
FAIL: test_is_backing_off_true (masu.test.providers.test_status.ProviderStatusTest)
Test is_backing_off() is true within the appropriate time window.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-koku/koku/koku/masu/test/providers/test_status.py", line 198, in test_is_backing_off_true
    self.assertTrue(accessor.is_backing_off())
AssertionError: False is not true
```

**Comment by maskarb** [comment] 2019-08-30 17:42
With parallel on:
```python
======================================================================
FAIL: test_download_bucket_with_prefix (masu.test.external.downloader.aws_local.test_aws_local_report_downloader.AWSLocalReportDownloaderTest)
Test to verify that basic report downloading works.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 605, in run
    testMethod()
  File "/Users/mskarbek/Documents/code/koku/koku/masu/test/external/downloader/aws_local/test_aws_local_report_downloader.py", line 159, in test_download_bucket_with_prefix
    self.assertTrue(os.path.isdir(expected_path))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true
```

**Comment by adberglund** [comment] 2019-09-25 18:10
```
ERROR: test_write_cost_model_rate_rbac_access (cost_models.test.tests_view.CostModelViewTests)
Test POST, PUT, and DELETE for rates with an rbac user.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-koku/koku/koku/cost_models/test/tests_view.py", line 436, in test_write_cost_model_rate_rbac_access
    self.initialize_request(context={'request_context': request_context, 'user_data': user_data})
  File "/home/travis/build/project-koku/koku/koku/cost_models/test/tests_view.py", line 65, in initialize_request
    self.provider = serializer.save()
  File "/home/travis/build/project-koku/koku/.tox/py36/lib/python3.6/site-packages/rest_framework/serializers.py", line 213, in save
    self.instance = self.create(validated_data)
  File "/opt/python/3.6.7/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/travis/build/project-koku/koku/koku/api/provider/serializers.py", line 182, in create
    raise serializers.ValidationError(error)
rest_framework.exceptions.ValidationError: {'Error': ErrorDetail(string='A Provider already exists with that Authentication and Billing Source', code='invalid')}
```

**Comment by adberglund** [comment] 2019-09-25 18:12
```
======================================================================
FAIL: test_populate_markup_cost (masu.test.database.test_aws_report_db_accessor.AWSReportDBAccessorTest)
Test that the daily summary table is populated.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/opt/python/3.7.1/lib/python3.7/unittest/mock.py", line 1191, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/project-koku/koku/koku/masu/test/database/test_aws_report_db_accessor.py", line 1309, in test_populate_markup_cost
    self.assertAlmostEqual(found_value, possible_value, 6)
AssertionError: Decimal('0.016686350') != Decimal('0.05852398000000000324873350444') within 6 places (Decimal('0.04183763000000000324873350444') difference)
```

**Comment by maskarb** [comment] 2019-10-16 20:47
```
======================================================================
FAIL: test_execute_query_with_tag_filter (api.report.test.tests_queries.ReportQueryTest)
Test that data is filtered by tag key.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/project-koku/koku/koku/api/report/test/tests_queries.py", line 1539, in test_execute_query_with_tag_filter
    self.assertEqual(result, totals[key])
AssertionError: Decimal('145.776300392') != Decimal('61.418383882')
```

**Comment by katherine-black** [comment] 2019-10-31 13:11
I spent a couple of days trying to reproduce these issues every which way, tried every tox config, I've tried different multiprocessing settings, I even tried to load the cpu on my machine with some video processing to try and increase potential load to tease out a failure, but alas, no luck :(

I'm closing this as can't reproduce, but if these issues ever crop back up we should consider reopening this issue.

**Comment by infinitewarp** [comment] 2019-10-31 17:33
Surprise! Mystery errors just happened again on two jobs in Travis:

```
======================================================================

ERROR: test_execute_query_w_delta (api.report.test.azure.tests_azure_query_handler.AzureReportQueryHandlerTest)

Test grouped by deltas.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/project-koku/koku/koku/api/report/test/azure/tests_azure_query_handler.py", line 762, in test_execute_query_w_delta

    usage_start__date__lte=self.dh.today.replace(month=self.dh.today.month - 1),

ValueError: day is out of range for month

======================================================================

FAIL: test_execute_query_w_delta_no_previous_data (api.report.test.tests_queries.ReportQueryTest)

Test deltas with no previous data.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/project-koku/koku/koku/api/report/test/tests_queries.py", line 1074, in test_execute_query_w_delta_no_previous_data

    self.assertAlmostEqual(delta.get('value'), expected_delta_value, 6)

AssertionError: Decimal('0') != Decimal('730.4404685424000036861446649') within 6 places

----------------------------------------------------------------------
```

```
======================================================================

ERROR: test_execute_query_w_delta (api.report.test.azure.tests_azure_query_handler.AzureReportQueryHandlerTest)

Test grouped by deltas.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/project-koku/koku/koku/api/report/test/azure/tests_azure_query_handler.py", line 762, in test_execute_query_w_delta

    usage_start__date__lte=self.dh.today.replace(month=self.dh.today.month - 1),

ValueError: day is out of range for month

======================================================================

FAIL: test_execute_query_w_delta_no_previous_data (api.report.test.tests_queries.ReportQueryTest)

Test deltas with no previous data.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/project-koku/koku/koku/api/report/test/tests_queries.py", line 1074, in test_execute_query_w_delta_no_previous_data

    self.assertAlmostEqual(delta.get('value'), expected_delta_value, 6)

AssertionError: Decimal('0') != Decimal('553.2527844822000027919726353') within 6 places (Decimal('553.2527844822000027919726353') difference)

----------------------------------------------------------------------
```

**Comment by katherine-black** [comment] 2019-11-01 13:25
@infinitewarp I wonder if its a travis environment specific error. I have a hunch, but I need more information to confirm it, could you provide links to the failing jobs?

**Comment by infinitewarp** [comment] 2019-11-01 13:49
https://travis-ci.org/project-koku/koku/jobs/605553998?utm_medium=notification&utm_source=github_status

https://travis-ci.org/project-koku/koku/jobs/605553999?utm_medium=notification&utm_source=github_status

**Comment by katherine-black** [comment] 2019-11-05 17:49
`test_execute_query_w_delta` failures were fixed in https://github.com/project-koku/koku/pull/1341

Still no way to reproduce the inconsistent calculations :(

**Comment by infinitewarp** [comment] 2019-11-05 19:13
I got a new and different flavor of flaky intermittent failure. This happened exactly once and only in the python 3.7 job, not the python 3.6 job (thought I really don't think the python version matters)

https://travis-ci.org/project-koku/koku/jobs/607791360?utm_medium=notification&utm_source=github_status
```
======================================================================

ERROR: test_ocp_cpu_query_group_by_cluster (api.report.test.ocp.test_ocp_query_handler.OCPReportQueryHandlerTest)

Test that group by cluster includes cluster and cluster_alias.

----------------------------------------------------------------------

Traceback (most recent call last):

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/query.py", line 538, in get_or_create

    return self.get(**kwargs), False

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/query.py", line 408, in get

    self.model._meta.object_name

reporting.provider.ocp.models.OCPUsageReportPeriod.DoesNotExist: OCPUsageReportPeriod matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "reporting_ocpusagereport_cluster_id_report_period_ff3ea314_uniq"

DETAIL:  Key (cluster_id, report_period_start, provider_id)=(investment, 2019-10-01 00:00:00+00, 5ece986d-d054-4d03-bf39-58a14d1e9757) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File "/home/travis/build/project-koku/koku/koku/api/report/test/ocp/test_ocp_query_handler.py", line 583, in test_ocp_cpu_query_group_by_cluster

    OCPReportDataGenerator(self.tenant, self.provider).add_data_to_tenant()

  File "/home/travis/build/project-koku/koku/koku/api/report/test/ocp/helpers.py", line 152, in add_data_to_tenant

    report_period = self.create_ocp_report_period(period, provider_uuid)

  File "/home/travis/build/project-koku/koku/koku/api/report/test/ocp/helpers.py", line 203, in create_ocp_report_period

    report_period, _ = OCPUsageReportPeriod.objects.get_or_create(**data)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/query.py", line 541, in get_or_create

    return self._create_object_from_params(kwargs, params)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/query.py", line 583, in _create_object_from_params

    raise e

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/query.py", line 575, in _create_object_from_params

    obj = self.create(**params)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/query.py", line 422, in create

    obj.save(force_insert=True, using=self.db)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/base.py", line 741, in save

    force_update=force_update, update_fields=update_fields)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/base.py", line 779, in save_base

    force_update, using, update_fields,

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/base.py", line 870, in _save_table

    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/base.py", line 908, in _do_insert

    using=using, raw=raw)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method

    return getattr(self.get_queryset(), name)(*args, **kwargs)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/query.py", line 1186, in _insert

    return query.get_compiler(using=using).execute_sql(return_id)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/models/sql/compiler.py", line 1335, in execute_sql

    cursor.execute(sql, params)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/backends/utils.py", line 67, in execute

    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/backends/utils.py", line 76, in _execute_with_wrappers

    return executor(sql, params, many, context)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/utils.py", line 89, in __exit__

    raise dj_exc_value.with_traceback(traceback) from exc_value

  File "/home/travis/build/project-koku/koku/.tox/for_travis/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute

    return self.cursor.execute(sql, params)

django.db.utils.IntegrityError: duplicate key value violates unique constraint "reporting_ocpusagereport_cluster_id_report_period_ff3ea314_uniq"

DETAIL:  Key (cluster_id, report_period_start, provider_id)=(investment, 2019-10-01 00:00:00+00, 5ece986d-d054-4d03-bf39-58a14d1e9757) already exists.


```

**Comment by infinitewarp** [comment] 2019-11-06 15:04
Rather than continue to reopen this issue as a catch-all, since @katherine-black found that at least _some_ of the reported errors have been fixed, I am _closing_ the current issue and advising any followers to open new issues for _specific_ errors as they present themselves.

**Closed by infinitewarp** 2019-11-06 15:04 UTC
Labels: bug, team-kokugrade
