### ISSUE TITLE
test_prefixed_logical_and travis failures

### ISSUE THREAD

**Issue by nbon12** [project-koku/koku#1611] opened 2020-01-10 20:15 UTC
The test test_prefixed_logical_and is occasionally causing travis failures. 

This can perhaps be remedied by namespacing the accounts that get added during the tests, so that there is no overlap with other data that gets added for other tests that might still be in the database.

**Comment by chambridge** [comment] 2020-01-10 20:24
This is a duplicate of the following bug: https://github.com/project-koku/koku/issues/1607

**Closed by chambridge** 2020-01-10 20:24 UTC
