### ISSUE TITLE
Integrate rates into OCP report queries

### ISSUE THREAD

**Issue by blentz** [project-koku/koku#435] opened 2018-10-23 14:33 UTC
## User Story
As Koku user, I want OCP queries to include rates so that I know how much OCP usage costs.

## Impacts
API

## Role
User

## Assumptions
- Rate model is implemented
- Rate CRUD operations are supported
- If no Rate exists that matches the Metric for a Line Item, the default price will be `0` and the default currency will be `USD`, applied as a fixed rate.

## Acceptance Criteria

- [ ] Report queries for OCP lineitems includes charge data (i.e. "totals")
- [ ] Charge data should use currency and metric units as defined by the rate

**Comment by chambridge** [comment] 2018-11-14 14:19
Duplicate of #362

**Closed by chambridge** 2018-11-14 14:19 UTC
Labels: currency, enhancement, ocp
