### ISSUE TITLE
Data stays in the database after removing the provider

### ISSUE THREAD

**Issue by dchorvat1** [project-koku/koku#1334] opened 2019-10-31 13:32 UTC
**Describe the bug**
After removing a provider, the data it had still showed up in the api endpoints.
Tested with OCP provider and nise data

**To Reproduce**
1. Add a provider, upload and ingest data
2. Delete the provider
3. Go to `/costs/` endpoint

**Expected behavior**
The data gets removed along with the provider

**Context (please complete the following information):**
 - Commit Hash from status endpoint: bd4c09a3344a512f9ef9ad7deefdfff5031cc0be

**Comment by lcouzens** [comment] 2019-11-05 19:37
Couldn't reproduce this and suspect it may have been related to #1328 so with that in mind I will close it for now. Feel free to reopen if we see this again.

**Closed by lcouzens** 2019-11-05 19:37 UTC
Labels: Koku'(x), bug
