### ISSUE TITLE
Deltas not being calculated in some cases

### ISSUE THREAD

**Issue by lcouzens** [project-koku/koku#723] opened 2019-03-11 15:31 UTC
**Describe the bug**
Deltas not being calculated in some cases

**To Reproduce**
1. Go to '?filter[resolution]=daily&filter[time_scope_units]=month&filter[time_scope_value]=-2&delta=cost'
```
    {
            "date": "2019-03-08",
            "values": [
                {
                    "date": "2019-03-08",
                    "infrastructure_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "derived_cost": {
                        "value": 70.86,
                        "units": "USD"
                    },
                    "cost": {
                        "value": 70.86,
                        "units": "USD"
                    },
                    "delta_value": 70.86,
                    "delta_percent": null
                }
            ]
        },
        {
            "date": "2019-03-09",
            "values": [
                {
                    "date": "2019-03-09",
                    "infrastructure_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "derived_cost": {
                        "value": 45.12,
                        "units": "USD"
                    },
                    "cost": {
                        "value": 45.12,
                        "units": "USD"
                    },
                    "delta_value": 45.12,
                    "delta_percent": null
                }
            ]
        },
        {
            "date": "2019-03-10",
            "values": [
                {
                    "date": "2019-03-10",
                    "infrastructure_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "derived_cost": {
                        "value": 45.12,
                        "units": "USD"
                    },
                    "cost": {
                        "value": 45.12,
                        "units": "USD"
                    },
                    "delta_value": 45.12,
                    "delta_percent": null
                }
            ]
        },
        {
            "date": "2019-03-11",
            "values": [
                {
                    "date": "2019-03-11",
                    "infrastructure_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "derived_cost": {
                        "value": 18.8,
                        "units": "USD"
                    },
                    "cost": {
                        "value": 18.8,
                        "units": "USD"
                    },
                    "delta_value": 18.8,
                    "delta_percent": null
                }
            ]
        }
    ]
```
**Expected behavior**
Deltas should be calculated if there is previous month data

**Context (please complete the following information):**
 - OS: Fedora
 - Browser: Firefox
 - Commit Hash from status endpoint: 4bc63891ac27ffa0365680bd83230bdc987d1cae

**Additional context**
The snippet above was from my account on CI

I also tried locally and got this when using monthly resolution:
```
{
            "date": "2019-02",
            "values": [
                {
                    "date": "2019-02",
                    "infrastructure_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "derived_cost": {
                        "value": 3548.16,
                        "units": "USD"
                    },
                    "cost": {
                        "value": 3548.16,
                        "units": "USD"
                    },
                    "delta_value": 3548.16,
                    "delta_percent": null
                }
            ]
        },
        {
            "date": "2019-03",
            "values": [
                {
                    "date": "2019-03",
                    "infrastructure_cost": {
                        "value": 0.0,
                        "units": "USD"
                    },
                    "derived_cost": {
                        "value": 1341.12,
                        "units": "USD"
                    },
                    "cost": {
                        "value": 1341.12,
                        "units": "USD"
                    },
                    "delta_value": 1341.12,
                    "delta_percent": null
                }
```

**Comment by blentz** [comment] 2019-03-11 18:48
This is not a bug. This is the expected behavior when the previous value is zero. Dividing by zero is undefined.

Delta percent is calculated with this formula: `(current_value - previous_value) / previous_value * 100`

**Comment by blentz** [comment] 2019-03-11 20:17
On further discussion, there's more here that we need to consider and address.

The UI has a requirements of needing to show a cost-to-date (e.g. Sum all costs from first of the month through today.) and be able to provide a delta for the same time range in the previous month.

This probably will require us to lift the serializer's restriction on only allowing -10 and -30 to be valid values for `time_scope_value`.

We may also want to consider lifting the restriction that `resolution` must match `time_scope_units` to enable the UI to request a monthly roll-up response even when `time_scope_value=day`.

**Comment by chambridge** [comment] 2019-03-14 00:04
time scope reverted, so closing this. Feel free to reopen if needed.

**Closed by chambridge** 2019-03-14 00:04 UTC
Labels: bug, priority - high
