### ISSUE TITLE
Free space of clusters and projects

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#1396] opened 2019-11-12 22:10 UTC
Note: This is a place holder for a "backlog review" discussion

As a user, I want the details view to include the free space of clusters and projects (i.e., what is not being used). For example, we need to view everything that is not in a project. 

If we group-by clusters, it would be ideal if we see the free space for each cluster. Thus, users could sort by what is using the most usage. We could also show this for the "top clusters" or "top projects".

**This issue is ON HOLD until we agree on the UX, and we have appropriate API changes from https://github.com/project-koku/koku/issues/1232.**

**Comment by dlabrecq** [comment] 2019-11-12 22:17
//cc @nlcwong @chargio

**Comment by dlabrecq** [comment] 2019-11-12 22:24
@nlcwong Is this a dup of https://github.com/project-koku/koku/issues/1232

**Comment by nlcwong** [comment] 2019-11-26 08:49
![OCPCloudInfraDetails](https://user-images.githubusercontent.com/31672086/69613456-9a6af780-0fff-11ea-9bcb-6408f3495475.png)

What the group by cluster would look like with the additional unused capacity information listed in the expanded panel of a cluster.

**Comment by nlcwong** [comment] 2019-11-26 08:54
@dlabrecq latest mocks, please comment: https://marvelapp.com/1jj511j6 (slide 7)

**Comment by dlabrecq** [comment] 2019-11-29 04:09
We won't know the cost on a particular day (e.g., Oct 20). All we have is the delta for last month. We can use the delta to calculate the difference between the current & previous month, but a particular date would require an API change.

**Comment by dlabrecq** [comment] 2019-11-29 04:09
@nlcwong We won't know the cost on a particular day (e.g., Oct 20). All we have is the delta for last month. We can use the delta to calculate the difference between the current & previous month, but a particular date would require an API change.

**Comment by nlcwong** [comment] 2019-12-03 02:51
I'm not looking for the daily, I'm looking for the cumulative.  Meaning, if today is 20-Oct and the cumulative cost month to date (1-20 Oct) is $40, what I want to know is what was the cumulative cost of the previous month to what would've been the date (1-20 Sep)?  I think adding/subtracting the delta would give us that number.  @adberglund is this a correct assumption for the math I just did?

**Comment by nlcwong** [comment] 2019-12-03 03:02
@dlabrecq RE: duplicate of #1232 I think this can serve as the UI portion of the overall need to show free space, the other issue could be used for any backend/API changes that needs to happen.  Although if the backend doesn't have to do any work, then we should just kill one of these issues and mark as a duplicate... preferably this one since the other one has a ton of comments in it that chronicled the decision discussion.

**Comment by jlalbertson** [comment] 2019-12-03 18:23
Closing as a duplicate of #1232.

**Closed** 2019-12-03 18:23 UTC
Labels: enhancement, needs UI/UX, needs discussion, on hold
