### ISSUE TITLE
Add cluster name to OCP charges report by default

### ISSUE THREAD

**Issue by dlabrecq** [project-koku/koku#716] opened 2019-03-06 23:49 UTC
## User Story
As a user, I want to see the cluster for each project.

## Impacts
Ex. API, UI, Docs

## Role
User

## Assumptions
- 
-

## API Details

| API  | Detail|
 | --- | --- |
 | **Method** | GET |
 | **Path** | /api/v1/reports/openshift/charges/ |
 | **Body** |  |
 | **Response** | |

## UI Details
I can get the cluster for each project using the API below, using `group_by[cluster]=*&group_by[project]=metering-hccm`. However, this is an additional request for the UI.

/r/insights/platform/cost-management/v1/reports/openshift/charges/?filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&filter[limit]=5&group_by[cluster]=*&group_by[project]=metering-hccm

![screen shot 2019-03-06 at 6 43 45 pm](https://user-images.githubusercontent.com/17481322/53921798-cee8ee80-403f-11e9-9554-90dc91ba15a2.png)

Considering we've already requested all the project costs, I'd like to see the cluster name included in the API below by default, so we don't need to make multiple requests.

https://ci.foo.redhat.com:1337/r/insights/platform/cost-management/v1/reports/openshift/charges/?delta=cost&filter[time_scope_units]=month&filter[time_scope_value]=-1&filter[resolution]=monthly&group_by[project]=*&order_by[cost]=desc

![screen shot 2019-03-06 at 6 44 26 pm](https://user-images.githubusercontent.com/17481322/53921819-e32ceb80-403f-11e9-95df-c3a7ef0d6bea.png)

![screen shot 2019-03-06 at 6 41 40 pm](https://user-images.githubusercontent.com/17481322/53921734-85000880-403f-11e9-8cb4-c6d2c74d6390.png)

## Acceptance Criteria

- [ ] Don't need to make multiple requests to access cluster name
- [ ]

**Comment by chambridge** [comment] 2019-03-07 16:56
Duplicate of https://github.com/project-koku/koku/issues/711

**Closed by chambridge** 2019-03-07 16:56 UTC
Labels: bug
